# Generated by Django 2.2.7 on 2024-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=20, null=True)),
                ('cust_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_given', models.CharField(blank=True, max_length=200, null=True)),
                ('liscense_no', models.CharField(blank=True, max_length=150, null=True)),
                ('liscense_type', models.CharField(blank=True, max_length=200, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=200, null=True)),
                ('cust_id', models.CharField(blank=True, max_length=200, null=True)),
                ('car_id', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('to_place', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_days', models.CharField(blank=True, max_length=150, null=True)),
                ('rent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=150, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(blank=True, max_length=20, null=True)),
                ('trip_id', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint_type', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('car_id', models.CharField(blank=True, max_length=20, null=True)),
                ('rateper_km', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_charges', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_id', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=70, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_km', models.CharField(blank=True, max_length=200, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_km', models.CharField(blank=True, max_length=200, null=True)),
                ('total_kms', models.CharField(blank=True, max_length=200, null=True)),
                ('total_days', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('utype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
